name: Build edge container image
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build_container_image.yml
    with:
      platforms: linux/amd64
      cache: false
      tags: |
        type=edge,branch=main
        type=sha
    secrets: inherit