name: Build Container Image

on:
  workflow_call:
    inputs:
      cache:
        type: boolean
        default: true
      image:
        type: string
        default: ghcr.io/ghosteathuman/kopi-o-kosong
      tags:
        type: string

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
        id: buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ inputs.image }}
          tags: ${{ inputs.tags }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          provenance: false
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          push: ${{ inputs.image != '' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: ${{ inputs.cache }}
          cache-to: ${{ inputs.cache }}