name: Build Edge Container Image
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build_container_image.yml
    with:
      cache: false
      images: |
        ghcr.io/ghosteathuman/kopi-o-kosong
        ghosteathuman/kopi-o-kosong
      tags: |
        type=edge,branch=main
        type=sha,prefix=
    secrets: inherit